name: Mark Laszlo - Resume
title: Mark Laszlo - Resume


author: Mark

# Your email if you want it to be linked on the contact page
author_email: laszlomark90@gmail.com


repository: marklaszlo9/resume
github_username:  marklaszlo9
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown]

include:
  - _site

defaults:
  -
    scope:
      path: /megas/
    values:
      redirect: https://youtu.be/jvWN71nXd08
