name: Mark Laszlo - Resume
title: Mark Laszlo - Resume

# Short description (goes below the title; it will also be used in the RSS feed)
description: Lakókocsis nyaralás Görögországban – 3 darrab jól felszerelt,légkondicionált lakókocsik várja a pihenni vágyókat. A lakókocsik Korinoson, Paraliatól 5 kilóméterre találhatóak. A kemping széles, homokos tengerparttal rendelkezik. A lakókocsik a parttól 150méterre találhatóak.

# Your name, as you want it to appear underneath each post and in the footer
author: Mark

# Your email if you want it to be linked on the contact page
author_email: laszlomark90@gmail.com


repository: marklaszlo9/resume
github_username:  marklaszlo9
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown]

include:
  - _site
